spring:
  data:
    mongodb:
      database: library

logging:
  file: log/app-info.log
  pattern:
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
  level:
    root: INFO
    ru.otus.krivonos: TRACE
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org.hibernate: WARN